### ISSUE TITLE
Onboard only once

### ISSUE THREAD

**Issue by jkkicks** [jkkicks/SparkBot#8]
check database/ server nickname to see if member has already onboarded, if so: send ephemeral message stating it's been completed already and to reach out to mods for help.

Complete when user presses button, before the modal pops up. Onboarded before? no modal.

**Comment by abaawe** [comment]
I am looking for a way to send a set of information to a database and receive this data again... in real time, that is, in real time.... without any delay............. I do not want to use Node js, I don't want to use RealTime Databases, I don't want to use MoongoDB, just PHP, SQL, and JavaScript.
